export const pagesRoutes = [
  ["v-746cc4b7","/book.html",{"title":""},["/book","/book.md"]],
  ["v-79fdd481","/home.html",{"title":"Project home","icon":"home"},["/home","/home.md"]],
  ["v-184f4da6","/intro.html",{"title":"Intro Page","icon":"info"},["/intro","/intro.md"]],
  ["v-391c6e28","/language.html",{"title":""},["/language","/language.md"]],
  ["v-8daa1a0e","/",{"title":"Yuejia-Lai的知识库","icon":"favicon.ico"},["/index.html","/README.md"]],
  ["v-0e503981","/slide.html",{"title":"幻灯片页","icon":"slides"},["/slide","/slide.md"]],
  ["v-a94a8cca","/computer/",{"title":""},["/computer/index.html","/computer/README.md"]],
  ["v-fffb8e28","/guide/",{"title":"本站使用说明","icon":"iconfont icon-creative"},["/guide/index.html","/guide/README.md"]],
  ["v-d85ce82c","/me/about.html",{"title":""},["/me/about","/me/about.md"]],
  ["v-44d193f5","/maps/C++.html",{"title":""},["/maps/C++","/maps/C++.md"]],
  ["v-20034198","/maps/Java.html",{"title":""},["/maps/Java","/maps/Java.md"]],
  ["v-5a814a99","/posts/article10.html",{"title":"文章 10","icon":"edit"},["/posts/article10","/posts/article10.md"]],
  ["v-5c362338","/posts/article11.html",{"title":"文章 11","icon":"edit"},["/posts/article11","/posts/article11.md"]],
  ["v-5deafbd7","/posts/article12.html",{"title":"文章 12","icon":"edit"},["/posts/article12","/posts/article12.md"]],
  ["v-7beb5be1","/posts/article9.html",{"title":"文章 9","icon":"edit"},["/posts/article9","/posts/article9.md"]],
  ["v-62727154","/tools/Git.html",{"title":"Git"},["/tools/Git","/tools/Git.md"]],
  ["v-63f85fdb","/tools/maven.html",{"title":"Maven"},["/tools/maven","/tools/maven.md"]],
  ["v-4c8e6f72","/use/disable.html",{"title":"布局与功能禁用","icon":"config"},["/use/disable","/use/disable.md"]],
  ["v-13188615","/use/encrypt.html",{"title":"密码加密的文章","icon":"lock"},["/use/encrypt","/use/encrypt.md"]],
  ["v-3ab95e2e","/use/markdown.html",{"title":"Markdown 展示","icon":"markdown"},["/use/markdown","/use/markdown.md"]],
  ["v-d677d26e","/use/page.html",{"title":"页面配置","icon":"page"},["/use/page","/use/page.md"]],
  ["v-03842690","/posts/article/article1.html",{"title":"文章 1","icon":"edit"},["/posts/article/article1","/posts/article/article1.md"]],
  ["v-0538ff2f","/posts/article/article2.html",{"title":"文章 2","icon":"edit"},["/posts/article/article2","/posts/article/article2.md"]],
  ["v-06edd7ce","/posts/article/article3.html",{"title":"文章 3","icon":"edit"},["/posts/article/article3","/posts/article/article3.md"]],
  ["v-08a2b06d","/posts/article/article4.html",{"title":"文章 4","icon":"edit"},["/posts/article/article4","/posts/article/article4.md"]],
  ["v-0a57890c","/posts/article/article5.html",{"title":"文章 5","icon":"edit"},["/posts/article/article5","/posts/article/article5.md"]],
  ["v-0c0c61ab","/posts/article/article6.html",{"title":"文章 6","icon":"edit"},["/posts/article/article6","/posts/article/article6.md"]],
  ["v-0dc13a4a","/posts/article/article7.html",{"title":"文章 7","icon":"edit"},["/posts/article/article7","/posts/article/article7.md"]],
  ["v-0f7612e9","/posts/article/article8.html",{"title":"文章 8","icon":"edit"},["/posts/article/article8","/posts/article/article8.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
  ["v-c684f322","/guide/.~README.html",{"title":""},["/guide/.~README","/guide/.~README.md"]],
]
