export const pagesRoutes = [
  ["v-746cc4b7","/book.html",{"title":""},["/book","/book.md"]],
  ["v-79fdd481","/home.html",{"title":"Project home","icon":"home"},["/home","/home.md"]],
  ["v-184f4da6","/intro.html",{"title":"Intro Page","icon":"info"},["/intro","/intro.md"]],
  ["v-391c6e28","/language.html",{"title":""},["/language","/language.md"]],
  ["v-8daa1a0e","/",{"title":"Yuejia-Lai的知识库","icon":"favicon.ico"},["/index.html","/README.md"]],
  ["v-0e503981","/slide.html",{"title":"幻灯片页","icon":"slides"},["/slide","/slide.md"]],
  ["v-a94a8cca","/computer/",{"title":""},["/computer/index.html","/computer/README.md"]],
  ["v-fffb8e28","/guide/",{"title":"本站使用说明","icon":"iconfont icon-creative"},["/guide/index.html","/guide/README.md"]],
  ["v-44d193f5","/maps/C++.html",{"title":""},["/maps/C++","/maps/C++.md"]],
  ["v-20034198","/maps/Java.html",{"title":"Java后端学习路线","icon":"iconfont icon-java"},["/maps/Java","/maps/Java.md"]],
  ["v-d85ce82c","/me/about.html",{"title":""},["/me/about","/me/about.md"]],
  ["v-08b90a7d","/tips/cmd.html",{"title":"cmd使用","icon":"iconfont icon-zhongduan"},["/tips/cmd","/tips/cmd.md"]],
  ["v-7620dd6c","/tips/markdown.html",{"title":"markdown语法","icon":"iconfont icon-file-markdown-fill"},["/tips/markdown","/tips/markdown.md"]],
  ["v-717c18d0","/tips/%E5%BC%80%E6%BA%90%E5%8D%8F%E8%AE%AE.html",{"title":"常见开源协议","icon":"iconfont icon-kaiyuan"},["/tips/开源协议.html","/tips/%E5%BC%80%E6%BA%90%E5%8D%8F%E8%AE%AE","/tips/开源协议.md","/tips/%E5%BC%80%E6%BA%90%E5%8D%8F%E8%AE%AE.md"]],
  ["v-62727154","/tools/Git.html",{"title":"Git","icon":"iconfont icon-git"},["/tools/Git","/tools/Git.md"]],
  ["v-63f85fdb","/tools/maven.html",{"title":"Maven","icon":"iconfont icon-G-stack-fill"},["/tools/maven","/tools/maven.md"]],
  ["v-ca16eb08","/computer/csapp/chapter1.html",{"title":"计算机系统漫游"},["/computer/csapp/chapter1","/computer/csapp/chapter1.md"]],
  ["v-c6ad39ca","/computer/csapp/chapter2.html",{"title":"信息的表示和处理"},["/computer/csapp/chapter2","/computer/csapp/chapter2.md"]],
  ["v-c343888c","/computer/csapp/chapter3.html",{"title":"程序的机器级表示"},["/computer/csapp/chapter3","/computer/csapp/chapter3.md"]],
  ["v-5783f7f9","/computer/csapp/",{"title":"CSAPP导读"},["/computer/csapp/index.html","/computer/csapp/README.md"]],
  ["v-070e12f9","/computer/SQL/chapter1.html",{"title":"数据库与MySQL环境搭建","icon":"iconfont icon-database-full"},["/computer/SQL/chapter1","/computer/SQL/chapter1.md"]],
  ["v-08c2eb98","/computer/SQL/chapter2.html",{"title":"基本SELECT语句","icon":"iconfont icon-database-full"},["/computer/SQL/chapter2","/computer/SQL/chapter2.md"]],
  ["v-0a77c437","/computer/SQL/chapter3.html",{"title":""},["/computer/SQL/chapter3","/computer/SQL/chapter3.md"]],
  ["v-1aba9716","/computer/C_Primer_plus/chapter1.html",{"title":"初识C语言"},["/computer/C_Primer_plus/chapter1","/computer/C_Primer_plus/chapter1.md"]],
  ["v-1750e5d8","/computer/C_Primer_plus/chapter2.html",{"title":"C语言概述"},["/computer/C_Primer_plus/chapter2","/computer/C_Primer_plus/chapter2.md"]],
  ["v-cec7e540","/computer/C_Primer_plus/",{"title":""},["/computer/C_Primer_plus/index.html","/computer/C_Primer_plus/README.md"]],
  ["v-94592aba","/develop/spring/SpringBoot.html",{"title":"SpringBoot","icon":"iconfont icon-bxl-spring-boot"},["/develop/spring/SpringBoot","/develop/spring/SpringBoot.md"]],
  ["v-8e320f7a","/develop/spring/SpringMVC.html",{"title":"SpringMVC","icon":"iconfont icon-bxl-spring-boot"},["/develop/spring/SpringMVC","/develop/spring/SpringMVC.md"]],
  ["v-68dec8fb","/java/javacore/chapter1.html",{"title":"Java程序设计概述"},["/java/javacore/chapter1","/java/javacore/chapter1.md"]],
  ["v-6a93a19a","/java/javacore/chapter2.html",{"title":"Java程序设计环境"},["/java/javacore/chapter2","/java/javacore/chapter2.md"]],
  ["v-6c487a39","/java/javacore/chapter3.html",{"title":"Java的基本程序设计结构"},["/java/javacore/chapter3","/java/javacore/chapter3.md"]],
  ["v-6dfd52d8","/java/javacore/chapter4.html",{"title":"对象和类"},["/java/javacore/chapter4","/java/javacore/chapter4.md"]],
  ["v-8809d1cc","/java/javacore/",{"title":"Java核心技术导读"},["/java/javacore/index.html","/java/javacore/README.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]
