export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"Yuejia-Lai的知识库","icon":"favicon.ico"},["/index.html","/README.md"]],
  ["v-746cc4b7","/book.html",{"title":""},["/book","/book.md"]],
  ["v-79fdd481","/home.html",{"title":"Project home","icon":"home"},["/home","/home.md"]],
  ["v-184f4da6","/intro.html",{"title":"Intro Page","icon":"info"},["/intro","/intro.md"]],
  ["v-391c6e28","/language.html",{"title":""},["/language","/language.md"]],
  ["v-0e503981","/slide.html",{"title":"幻灯片页","icon":"slides"},["/slide","/slide.md"]],
  ["v-a94a8cca","/computer/",{"title":""},["/computer/index.html","/computer/README.md"]],
  ["v-fffb8e28","/guide/",{"title":"本站使用说明","icon":"iconfont icon-creative"},["/guide/index.html","/guide/README.md"]],
  ["v-44d193f5","/maps/C++.html",{"title":""},["/maps/C++","/maps/C++.md"]],
  ["v-20034198","/maps/Java.html",{"title":"Java后端学习路线","icon":"iconfont icon-java"},["/maps/Java","/maps/Java.md"]],
  ["v-d85ce82c","/me/about.html",{"title":""},["/me/about","/me/about.md"]],
  ["v-08b90a7d","/tips/cmd.html",{"title":"cmd使用","icon":"iconfont icon-zhongduan"},["/tips/cmd","/tips/cmd.md"]],
  ["v-7620dd6c","/tips/markdown.html",{"title":"markdown语法","icon":"iconfont icon-file-markdown-fill"},["/tips/markdown","/tips/markdown.md"]],
  ["v-717c18d0","/tips/%E5%BC%80%E6%BA%90%E5%8D%8F%E8%AE%AE.html",{"title":"常见开源协议","icon":"iconfont icon-kaiyuan"},["/tips/开源协议.html","/tips/%E5%BC%80%E6%BA%90%E5%8D%8F%E8%AE%AE","/tips/开源协议.md","/tips/%E5%BC%80%E6%BA%90%E5%8D%8F%E8%AE%AE.md"]],
  ["v-62727154","/tools/Git.html",{"title":"Git","icon":"iconfont icon-git"},["/tools/Git","/tools/Git.md"]],
  ["v-63f85fdb","/tools/maven.html",{"title":"Maven","icon":"iconfont icon-G-stack-fill"},["/tools/maven","/tools/maven.md"]],
  ["v-5909d864","/develop/MyBatis/chapter1.html",{"title":"MyBatis简介","icon":"iconfont icon-data"},["/develop/MyBatis/chapter1","/develop/MyBatis/chapter1.md"]],
  ["v-55a02726","/develop/MyBatis/chapter2.html",{"title":"搭建MyBatis","icon":"iconfont icon-data"},["/develop/MyBatis/chapter2","/develop/MyBatis/chapter2.md"]],
  ["v-523675e8","/develop/MyBatis/chapter3.html",{"title":"MyBatis的增删改查","icon":"iconfont icon-data"},["/develop/MyBatis/chapter3","/develop/MyBatis/chapter3.md"]],
  ["v-4eccc4aa","/develop/MyBatis/chapter4.html",{"title":"MyBatis获取参数值的两种方式","icon":"iconfont icon-data"},["/develop/MyBatis/chapter4","/develop/MyBatis/chapter4.md"]],
  ["v-4b63136c","/develop/MyBatis/chapter5.html",{"title":"MyBatis的各种查询功能","icon":"iconfont icon-data"},["/develop/MyBatis/chapter5","/develop/MyBatis/chapter5.md"]],
  ["v-47f9622e","/develop/MyBatis/chapter6.html",{"title":"自定义映射resultMap","icon":"iconfont icon-data"},["/develop/MyBatis/chapter6","/develop/MyBatis/chapter6.md"]],
  ["v-448fb0f0","/develop/MyBatis/chapter7.html",{"title":"动态SQL","icon":"iconfont icon-data"},["/develop/MyBatis/chapter7","/develop/MyBatis/chapter7.md"]],
  ["v-4125ffb2","/develop/MyBatis/chapter8.html",{"title":"MyBatis的缓存与逆向工程","icon":"iconfont icon-data"},["/develop/MyBatis/chapter8","/develop/MyBatis/chapter8.md"]],
  ["v-3dbc4e74","/develop/MyBatis/chapter9.html",{"title":"分页插件","icon":"iconfont icon-data"},["/develop/MyBatis/chapter9","/develop/MyBatis/chapter9.md"]],
  ["v-7ab5dc4a","/develop/MyBatis%20Plus/chapter1.html",{"title":"MyBatis-Plus简介与入门案例","icon":"iconfont icon-sharpicons_database-center"},["/develop/MyBatis Plus/chapter1.html","/develop/MyBatis%20Plus/chapter1","/develop/MyBatis Plus/chapter1.md","/develop/MyBatis%20Plus/chapter1.md"]],
  ["v-774c2b0c","/develop/MyBatis%20Plus/chapter2.html",{"title":"基本CRUD与常用注解","icon":"iconfont icon-sharpicons_database-center"},["/develop/MyBatis Plus/chapter2.html","/develop/MyBatis%20Plus/chapter2","/develop/MyBatis Plus/chapter2.md","/develop/MyBatis%20Plus/chapter2.md"]],
  ["v-73e279ce","/develop/MyBatis%20Plus/chapter3.html",{"title":"条件构造器与常用接口和插件","icon":"iconfont icon-sharpicons_database-center"},["/develop/MyBatis Plus/chapter3.html","/develop/MyBatis%20Plus/chapter3","/develop/MyBatis Plus/chapter3.md","/develop/MyBatis%20Plus/chapter3.md"]],
  ["v-7078c890","/develop/MyBatis%20Plus/chapter4.html",{"title":"通用枚举，代码生成器与多数据源配置","icon":"iconfont icon-sharpicons_database-center"},["/develop/MyBatis Plus/chapter4.html","/develop/MyBatis%20Plus/chapter4","/develop/MyBatis Plus/chapter4.md","/develop/MyBatis%20Plus/chapter4.md"]],
  ["v-26d0d5b0","/develop/SSM/chapter1.html",{"title":"SSM整合总结","icon":"iconfont icon-bxl-spring-boot"},["/develop/SSM/chapter1","/develop/SSM/chapter1.md"]],
  ["v-23672472","/develop/SSM/chapter2.html",{"title":"SSM整合","icon":"iconfont icon-bxl-spring-boot"},["/develop/SSM/chapter2","/develop/SSM/chapter2.md"]],
  ["v-91b00d44","/develop/Spring/chapter1.html",{"title":"Spring简介","icon":"iconfont icon-bxl-spring-boot"},["/develop/Spring/chapter1","/develop/Spring/chapter1.md"]],
  ["v-8e465c06","/develop/Spring/chapter2.html",{"title":"IOC","icon":"iconfont icon-bxl-spring-boot"},["/develop/Spring/chapter2","/develop/Spring/chapter2.md"]],
  ["v-8adcaac8","/develop/Spring/chapter3.html",{"title":"AOP","icon":"iconfont icon-bxl-spring-boot"},["/develop/Spring/chapter3","/develop/Spring/chapter3.md"]],
  ["v-8772f98a","/develop/Spring/chapter4.html",{"title":"声明式事务","icon":"iconfont icon-bxl-spring-boot"},["/develop/Spring/chapter4","/develop/Spring/chapter4.md"]],
  ["v-5c5f74f0","/develop/SpringBoot/chapter1.html",{"title":"快速上手SpringBoot","icon":"iconfont icon-bxl-spring-boot"},["/develop/SpringBoot/chapter1","/develop/SpringBoot/chapter1.md"]],
  ["v-5e144d8f","/develop/SpringBoot/chapter2.html",{"title":"SpringBoot基础配置","icon":"iconfont icon-bxl-spring-boot"},["/develop/SpringBoot/chapter2","/develop/SpringBoot/chapter2.md"]],
  ["v-5fc9262e","/develop/SpringBoot/chapter3.html",{"title":"基于SpringBoot实现SSMP整合","icon":"iconfont icon-bxl-spring-boot"},["/develop/SpringBoot/chapter3","/develop/SpringBoot/chapter3.md"]],
  ["v-00b24c30","/develop/SpringMVC/chapter1.html",{"title":"SpringMVC简介与入门案例","icon":"iconfont icon-bxl-spring-boot"},["/develop/SpringMVC/chapter1","/develop/SpringMVC/chapter1.md"]],
  ["v-015bb287","/develop/SpringMVC/chapter2.html",{"title":"RequestMapping注解与请求参数获取","icon":"iconfont icon-bxl-spring-boot"},["/develop/SpringMVC/chapter2","/develop/SpringMVC/chapter2.md"]],
  ["v-03108b26","/develop/SpringMVC/chapter3.html",{"title":"域对象共享数据与视图","icon":"iconfont icon-bxl-spring-boot"},["/develop/SpringMVC/chapter3","/develop/SpringMVC/chapter3.md"]],
  ["v-04c563c5","/develop/SpringMVC/chapter4.html",{"title":"RESTful","icon":"iconfont icon-bxl-spring-boot"},["/develop/SpringMVC/chapter4","/develop/SpringMVC/chapter4.md"]],
  ["v-067a3c64","/develop/SpringMVC/chapter5.html",{"title":"ajax请求与文件上传和下载","icon":"iconfont icon-bxl-spring-boot"},["/develop/SpringMVC/chapter5","/develop/SpringMVC/chapter5.md"]],
  ["v-082f1503","/develop/SpringMVC/chapter6.html",{"title":"拦截器与异常处理器","icon":"iconfont icon-bxl-spring-boot"},["/develop/SpringMVC/chapter6","/develop/SpringMVC/chapter6.md"]],
  ["v-09e3eda2","/develop/SpringMVC/chapter7.html",{"title":"注解配置SpringMVC与执行流程","icon":"iconfont icon-bxl-spring-boot"},["/develop/SpringMVC/chapter7","/develop/SpringMVC/chapter7.md"]],
  ["v-cec7e540","/computer/C_Primer_plus/",{"title":""},["/computer/C_Primer_plus/index.html","/computer/C_Primer_plus/README.md"]],
  ["v-1aba9716","/computer/C_Primer_plus/chapter1.html",{"title":"初识C语言"},["/computer/C_Primer_plus/chapter1","/computer/C_Primer_plus/chapter1.md"]],
  ["v-1750e5d8","/computer/C_Primer_plus/chapter2.html",{"title":"C语言概述"},["/computer/C_Primer_plus/chapter2","/computer/C_Primer_plus/chapter2.md"]],
  ["v-7b704b42","/computer/Linux/chapter1.html",{"title":"Linux目录结构","icon":"iconfont icon-linux"},["/computer/Linux/chapter1","/computer/Linux/chapter1.md"]],
  ["v-78069a04","/computer/Linux/chapter2.html",{"title":"Vi与Vim","icon":"iconfont icon-linux"},["/computer/Linux/chapter2","/computer/Linux/chapter2.md"]],
  ["v-749ce8c6","/computer/Linux/chapter3.html",{"title":"开机、重启和用户登录注销","icon":"iconfont icon-linux"},["/computer/Linux/chapter3","/computer/Linux/chapter3.md"]],
  ["v-71333788","/computer/Linux/chapter4.html",{"title":"用户管理","icon":"iconfont icon-linux"},["/computer/Linux/chapter4","/computer/Linux/chapter4.md"]],
  ["v-6dc9864a","/computer/Linux/chapter5.html",{"title":"实用指令","icon":"iconfont icon-linux"},["/computer/Linux/chapter5","/computer/Linux/chapter5.md"]],
  ["v-6a5fd50c","/computer/Linux/chapter6.html",{"title":"组管理和权限管理","icon":"iconfont icon-linux"},["/computer/Linux/chapter6","/computer/Linux/chapter6.md"]],
  ["v-66f623ce","/computer/Linux/chapter7.html",{"title":"定时任务调度","icon":"iconfont icon-linux"},["/computer/Linux/chapter7","/computer/Linux/chapter7.md"]],
  ["v-638c7290","/computer/Linux/chapter8.html",{"title":"Linux 磁盘分区、挂载","icon":"iconfont icon-linux"},["/computer/Linux/chapter8","/computer/Linux/chapter8.md"]],
  ["v-070e12f9","/computer/SQL/chapter1.html",{"title":"数据库与MySQL环境搭建","icon":"iconfont icon-database-full"},["/computer/SQL/chapter1","/computer/SQL/chapter1.md"]],
  ["v-4a315eee","/computer/SQL/chapter10.html",{"title":"变量、流程控制与游标、触发器","icon":"iconfont icon-database-full"},["/computer/SQL/chapter10","/computer/SQL/chapter10.md"]],
  ["v-46c7adb0","/computer/SQL/chapter11.html",{"title":"MySQL 8 新特性","icon":"iconfont icon-database-full"},["/computer/SQL/chapter11","/computer/SQL/chapter11.md"]],
  ["v-08c2eb98","/computer/SQL/chapter2.html",{"title":"基本SELECT语句","icon":"iconfont icon-database-full"},["/computer/SQL/chapter2","/computer/SQL/chapter2.md"]],
  ["v-0a77c437","/computer/SQL/chapter3.html",{"title":"多表查询","icon":"iconfont icon-database-full"},["/computer/SQL/chapter3","/computer/SQL/chapter3.md"]],
  ["v-0c2c9cd6","/computer/SQL/chapter4.html",{"title":"单行函数与聚合函数","icon":"iconfont icon-database-full"},["/computer/SQL/chapter4","/computer/SQL/chapter4.md"]],
  ["v-0de17575","/computer/SQL/chapter5.html",{"title":"子查询","icon":"iconfont icon-database-full"},["/computer/SQL/chapter5","/computer/SQL/chapter5.md"]],
  ["v-0f964e14","/computer/SQL/chapter6.html",{"title":"表操作与数据增删改","icon":"iconfont icon-database-full"},["/computer/SQL/chapter6","/computer/SQL/chapter6.md"]],
  ["v-114b26b3","/computer/SQL/chapter7.html",{"title":"数据类型","icon":"iconfont icon-database-full"},["/computer/SQL/chapter7","/computer/SQL/chapter7.md"]],
  ["v-12ffff52","/computer/SQL/chapter8.html",{"title":"约束","icon":"iconfont icon-database-full"},["/computer/SQL/chapter8","/computer/SQL/chapter8.md"]],
  ["v-14b4d7f1","/computer/SQL/chapter9.html",{"title":"视图、存储过程与函数","icon":"iconfont icon-database-full"},["/computer/SQL/chapter9","/computer/SQL/chapter9.md"]],
  ["v-5783f7f9","/computer/csapp/",{"title":"CSAPP导读"},["/computer/csapp/index.html","/computer/csapp/README.md"]],
  ["v-ca16eb08","/computer/csapp/chapter1.html",{"title":"计算机系统漫游"},["/computer/csapp/chapter1","/computer/csapp/chapter1.md"]],
  ["v-c6ad39ca","/computer/csapp/chapter2.html",{"title":"信息的表示和处理"},["/computer/csapp/chapter2","/computer/csapp/chapter2.md"]],
  ["v-c343888c","/computer/csapp/chapter3.html",{"title":"程序的机器级表示"},["/computer/csapp/chapter3","/computer/csapp/chapter3.md"]],
  ["v-8809d1cc","/java/javacore/",{"title":"Java核心技术导读"},["/java/javacore/index.html","/java/javacore/README.md"]],
  ["v-68dec8fb","/java/javacore/chapter1.html",{"title":"Java程序设计概述"},["/java/javacore/chapter1","/java/javacore/chapter1.md"]],
  ["v-6a93a19a","/java/javacore/chapter2.html",{"title":"Java程序设计环境"},["/java/javacore/chapter2","/java/javacore/chapter2.md"]],
  ["v-6c487a39","/java/javacore/chapter3.html",{"title":"Java的基本程序设计结构"},["/java/javacore/chapter3","/java/javacore/chapter3.md"]],
  ["v-6dfd52d8","/java/javacore/chapter4.html",{"title":"对象和类"},["/java/javacore/chapter4","/java/javacore/chapter4.md"]],
  ["v-7b8c448d","/leetcode/offer/offer-1.html",{"title":"剑指offer(第二版)-I","icon":"iconfont icon-leetcode1"},["/leetcode/offer/offer-1","/leetcode/offer/offer-1.md"]],
  ["v-7d411d2c","/leetcode/offer/offer-2.html",{"title":"剑指offer(第二版)-II","icon":"iconfont icon-leetcode1"},["/leetcode/offer/offer-2","/leetcode/offer/offer-2.md"]],
  ["v-7ef5f5cb","/leetcode/offer/offer-3.html",{"title":"剑指offer(第二版)-III","icon":"iconfont icon-leetcode1"},["/leetcode/offer/offer-3","/leetcode/offer/offer-3.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]
