export const data = JSON.parse("{\"key\":\"v-73e279ce\",\"path\":\"/develop/MyBatis%20Plus/chapter3.html\",\"title\":\"条件构造器与常用接口和插件\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"条件构造器与常用接口和插件\",\"icon\":\"iconfont icon-sharpicons_database-center\",\"date\":\"2022-09-30T00:00:00.000Z\"},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"wapper介绍\",\"slug\":\"wapper介绍\",\"children\":[]},{\"level\":2,\"title\":\"QueryWrapper\",\"slug\":\"querywrapper\",\"children\":[{\"level\":3,\"title\":\"组装查询条件\",\"slug\":\"组装查询条件\",\"children\":[]},{\"level\":3,\"title\":\"组装排序条件\",\"slug\":\"组装排序条件\",\"children\":[]},{\"level\":3,\"title\":\"组装删除条件\",\"slug\":\"组装删除条件\",\"children\":[]},{\"level\":3,\"title\":\"条件的优先级\",\"slug\":\"条件的优先级\",\"children\":[]},{\"level\":3,\"title\":\"组装select子句\",\"slug\":\"组装select子句\",\"children\":[]},{\"level\":3,\"title\":\"实现子查询\",\"slug\":\"实现子查询\",\"children\":[]}]},{\"level\":2,\"title\":\"UpdateWrapper\",\"slug\":\"updatewrapper\",\"children\":[]},{\"level\":2,\"title\":\"condition\",\"slug\":\"condition\",\"children\":[{\"level\":3,\"title\":\"思路一：\",\"slug\":\"思路一\",\"children\":[]},{\"level\":3,\"title\":\"思路二：\",\"slug\":\"思路二\",\"children\":[]}]},{\"level\":2,\"title\":\"LambdaQueryWrapper\",\"slug\":\"lambdaquerywrapper\",\"children\":[]},{\"level\":2,\"title\":\"LambdaUpdateWrapper\",\"slug\":\"lambdaupdatewrapper\",\"children\":[]},{\"level\":2,\"title\":\"分页插件\",\"slug\":\"分页插件\",\"children\":[{\"level\":3,\"title\":\"添加配置类\",\"slug\":\"添加配置类\",\"children\":[]},{\"level\":3,\"title\":\"测试\",\"slug\":\"测试\",\"children\":[]}]},{\"level\":2,\"title\":\"xml自定义分页\",\"slug\":\"xml自定义分页\",\"children\":[{\"level\":3,\"title\":\"UserMapper中定义接口方法\",\"slug\":\"usermapper中定义接口方法\",\"children\":[]},{\"level\":3,\"title\":\"UserMapper.xml中编写SQL\",\"slug\":\"usermapper-xml中编写sql\",\"children\":[]},{\"level\":3,\"title\":\"测试\",\"slug\":\"测试-1\",\"children\":[]}]},{\"level\":2,\"title\":\"乐观锁\",\"slug\":\"乐观锁\",\"children\":[{\"level\":3,\"title\":\"场景\",\"slug\":\"场景\",\"children\":[]},{\"level\":3,\"title\":\"乐观锁与悲观锁\",\"slug\":\"乐观锁与悲观锁\",\"children\":[]},{\"level\":3,\"title\":\"模拟修改冲突\",\"slug\":\"模拟修改冲突\",\"children\":[]},{\"level\":3,\"title\":\"乐观锁实现流程\",\"slug\":\"乐观锁实现流程\",\"children\":[]},{\"level\":3,\"title\":\"Mybatis-Plus实现乐观锁\",\"slug\":\"mybatis-plus实现乐观锁\",\"children\":[]}]}],\"readingTime\":{\"minutes\":9.74,\"words\":2921},\"copyright\":\"著作权归Yuejia-Lai所有\\n原文链接：https://laiyuejia.cn/develop/MyBatis%20Plus/chapter3.html\",\"filePathRelative\":\"develop/MyBatis Plus/chapter3.md\",\"localizedDate\":\"2022年9月30日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
